FROM bitwalker/alpine-elixir:1.4.0

MAINTAINER XOfSpades

RUN apk add --update bash && rm -rf /var/cache/apk/*

EXPOSE 8080

RUN mix local.hex --force && \
    mix local.rebar --force

RUN mkdir /training

WORKDIR /training

RUN mkdir /training/_build
RUN mkdir -p /training/config
RUN mkdir /training/lib

COPY mix.exs /training/mix.exs
COPY mix.lock /training/mix.lock

RUN MIX_ENV=test mix do deps.get, deps.compile

COPY config/config.exs /training/config/config.exs
COPY config/test.exs /training/config/test.exs

# When using a database
# COPY priv /training/priv

COPY lib /training/lib
COPY web /training/web
COPY test /training/test

RUN MIX_ENV=test mix compile
